# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0UejdoZ9ka3G828XEdAVtW3aVF42luq
"""

import streamlit as st
from recommender import recommend

st.set_page_config(page_title="Netflix Recommender", layout="wide")
st.markdown("<h1 style='color:red;'>🍿 Netflix Recommendation Engine</h1>", unsafe_allow_html=True)

movie_input = st.text_input("Enter a Netflix title", "")

if movie_input:
    results = recommend(movie_input)

    if len(results) == 0:
        st.error("Sorry, no matching title found.")
    else:
        st.success("Here are similar titles you might like:")
        cols = st.columns(2)
        for idx, row in results.iterrows():
            with cols[idx % 2]:
                st.subheader(row['title'])
                st.write(f"**Genre:** {row['listed_in']}")
                st.caption(row['description'][:200] + "...")