# -*- coding: utf-8 -*-
"""recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzjYXpRzaOGCcPix5WNEb_N4wQ1i2Jof
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

df = pd.read_csv('netflix_titles.csv')
df['description'] = df['description'].fillna('')
df['listed_in'] = df['listed_in'].fillna('')
df['text'] = df['description'] + ' ' + df['listed_in']

# Add after loading df
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['release_year'] = df['date_added'].dt.year

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['text'])

nn_model = NearestNeighbors(n_neighbors=6, metric='cosine')
nn_model.fit(tfidf_matrix)

def recommend(title):
    title = title.lower()
    matches = df[df['title'].str.lower() == title]
    if matches.empty:
        return []
    idx = matches.index[0]
    distances, indices = nn_model.kneighbors(tfidf_matrix[idx], n_neighbors=6)
    return df.iloc[indices[0][1:]][['title', 'listed_in', 'description']]
